import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full h-screen relative">
        <div className="absolute inset-0 -z-10 bg-slate-900">
          <div className="absolute rounded-full bg-teal-100 animate-ping top-52 right-52 w-52 h-52" />
          <div className="absolute rounded-full bg-teal-100 animate-ping top-52 left-12 w-52 h-52" />
          <div className="absolute rounded-full bg-teal-100 animate-ping bottom-[400px] left-[200px] w-52 h-52" />
        </div>
        {children}
      </body>
    </html>
  );
}
